spring.application.name=cinema

spring.datasource.url=jdbc:postgresql://localhost:5432/cinema_db
spring.datasource.username=postgres
spring.datasource.password=wlad2309
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true